--This file is NOT for use as code to run
--It's only a list with Agony's "enumerations"
CollectibleType = {
	--[...]
	AGONY_C_BREADY_MOLD,
	AGONY_C_BROTHER_CANCER,
	AGONY_C_CORNUCOPIA,
	AGONY_C_CYANIDE,
	AGONY_C_D3,
	AGONY_C_DOUBLE_DOWN,
	AGONY_C_ELECTRIC_HAIR,
	AGONY_C_GASOLINE_JB,
	AGONY_C_GROWING_ANXIETY,
	AGONY_C_HYPERACTIVE,
	AGONY_C_KIP, --Knowledge is Power
	AGONY_C_LOADED_DICE,
	AGONY_C_LSD, --Little Sugar Dumdum
	AGONY_C_LUCKY_LEG,
	AGONY_C_MAGIC_KIT,
	AGONY_C_OVERGROWN_SPINE,
	AGONY_C_PIP, --Powerty Is Power
	AGONY_C_PYRAMID_HEAD,
	AGONY_C_PYTHAGORE_BODY,
	AGONY_C_RADIOACTIVE_PIZZA,
	AGONY_C_REMEMBER_ME_NOW,
	AGONY_C_RUNESTONE,
	AGONY_C_SOLOMON_CROWN,
	AGONY_C_SUICIDE_GOD,
	AGONY_C_TANTRUM,
	AGONY_C_TDDUA, --Til Death Do Us Apart
	AGONY_C_THE_ROCK,
	AGONY_C_TECH_9000,
	AGONY_C_THE_BIG_ROCK,
	AGONY_C_TOURETTE,
	AGONY_C_TRIPLOPIA,
	AGONY_C_TUMOR,
	AGONY_C_URA_BIG_GUY, --You're a big Guy
	AGONY_C_VOMIT_CAKE,
	AGONY_C_WIP, --Wrath is Power
	AGONY_C_YEUX_REVOLVER
};

EntityType = {
	--[...]
	AGONY_ETYPE_TREASURE_HOARDER,
	AGONY_ETYPE_YELLOW_BLOCK
};

PillEffect = {
	--[...]
	AGONY_PEFF_PARTY_PILLS
};

--[^A-Za-z_0-9]\r